// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	worker "github.com/SyntaxErrorLineNULL/worker"
	mock "github.com/stretchr/testify/mock"
)

// Pool is an autogenerated mock type for the Pool type
type Pool struct {
	mock.Mock
}

type Pool_Expecter struct {
	mock *mock.Mock
}

func (_m *Pool) EXPECT() *Pool_Expecter {
	return &Pool_Expecter{mock: &_m.Mock}
}

// AddTaskInQueue provides a mock function with given fields: task
func (_m *Pool) AddTaskInQueue(task worker.Task) error {
	ret := _m.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for AddTaskInQueue")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(worker.Task) error); ok {
		r0 = rf(task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Pool_AddTaskInQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTaskInQueue'
type Pool_AddTaskInQueue_Call struct {
	*mock.Call
}

// AddTaskInQueue is a helper method to define mock.On call
//   - task worker.Task
func (_e *Pool_Expecter) AddTaskInQueue(task interface{}) *Pool_AddTaskInQueue_Call {
	return &Pool_AddTaskInQueue_Call{Call: _e.mock.On("AddTaskInQueue", task)}
}

func (_c *Pool_AddTaskInQueue_Call) Run(run func(task worker.Task)) *Pool_AddTaskInQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(worker.Task))
	})
	return _c
}

func (_c *Pool_AddTaskInQueue_Call) Return(_a0 error) *Pool_AddTaskInQueue_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pool_AddTaskInQueue_Call) RunAndReturn(run func(worker.Task) error) *Pool_AddTaskInQueue_Call {
	_c.Call.Return(run)
	return _c
}

// AddWorker provides a mock function with given fields: _a0
func (_m *Pool) AddWorker(_a0 worker.Worker) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for AddWorker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(worker.Worker) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Pool_AddWorker_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddWorker'
type Pool_AddWorker_Call struct {
	*mock.Call
}

// AddWorker is a helper method to define mock.On call
//   - _a0 worker.Worker
func (_e *Pool_Expecter) AddWorker(_a0 interface{}) *Pool_AddWorker_Call {
	return &Pool_AddWorker_Call{Call: _e.mock.On("AddWorker", _a0)}
}

func (_c *Pool_AddWorker_Call) Run(run func(_a0 worker.Worker)) *Pool_AddWorker_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(worker.Worker))
	})
	return _c
}

func (_c *Pool_AddWorker_Call) Return(_a0 error) *Pool_AddWorker_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pool_AddWorker_Call) RunAndReturn(run func(worker.Worker) error) *Pool_AddWorker_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function with no fields
func (_m *Pool) Run() {
	_m.Called()
}

// Pool_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Pool_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *Pool_Expecter) Run() *Pool_Run_Call {
	return &Pool_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *Pool_Run_Call) Run(run func()) *Pool_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Pool_Run_Call) Return() *Pool_Run_Call {
	_c.Call.Return()
	return _c
}

func (_c *Pool_Run_Call) RunAndReturn(run func()) *Pool_Run_Call {
	_c.Run(run)
	return _c
}

// RunningWorkers provides a mock function with no fields
func (_m *Pool) RunningWorkers() int32 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RunningWorkers")
	}

	var r0 int32
	if rf, ok := ret.Get(0).(func() int32); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int32)
	}

	return r0
}

// Pool_RunningWorkers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunningWorkers'
type Pool_RunningWorkers_Call struct {
	*mock.Call
}

// RunningWorkers is a helper method to define mock.On call
func (_e *Pool_Expecter) RunningWorkers() *Pool_RunningWorkers_Call {
	return &Pool_RunningWorkers_Call{Call: _e.mock.On("RunningWorkers")}
}

func (_c *Pool_RunningWorkers_Call) Run(run func()) *Pool_RunningWorkers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Pool_RunningWorkers_Call) Return(_a0 int32) *Pool_RunningWorkers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Pool_RunningWorkers_Call) RunAndReturn(run func() int32) *Pool_RunningWorkers_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *Pool) Stop() {
	_m.Called()
}

// Pool_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Pool_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Pool_Expecter) Stop() *Pool_Stop_Call {
	return &Pool_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Pool_Stop_Call) Run(run func()) *Pool_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Pool_Stop_Call) Return() *Pool_Stop_Call {
	_c.Call.Return()
	return _c
}

func (_c *Pool_Stop_Call) RunAndReturn(run func()) *Pool_Stop_Call {
	_c.Run(run)
	return _c
}

// NewPool creates a new instance of Pool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *Pool {
	mock := &Pool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
