// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Processing is an autogenerated mock type for the Processing type
type Processing struct {
	mock.Mock
}

type Processing_Expecter struct {
	mock *mock.Mock
}

func (_m *Processing) EXPECT() *Processing_Expecter {
	return &Processing_Expecter{mock: &_m.Mock}
}

// Processing provides a mock function with given fields: ctx, input
func (_m *Processing) Processing(ctx context.Context, input interface{}) {
	_m.Called(ctx, input)
}

// Processing_Processing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Processing'
type Processing_Processing_Call struct {
	*mock.Call
}

// Processing is a helper method to define mock.On call
//   - ctx context.Context
//   - input interface{}
func (_e *Processing_Expecter) Processing(ctx interface{}, input interface{}) *Processing_Processing_Call {
	return &Processing_Processing_Call{Call: _e.mock.On("Processing", ctx, input)}
}

func (_c *Processing_Processing_Call) Run(run func(ctx context.Context, input interface{})) *Processing_Processing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}))
	})
	return _c
}

func (_c *Processing_Processing_Call) Return() *Processing_Processing_Call {
	_c.Call.Return()
	return _c
}

func (_c *Processing_Processing_Call) RunAndReturn(run func(context.Context, interface{})) *Processing_Processing_Call {
	_c.Run(run)
	return _c
}

// NewProcessing creates a new instance of Processing. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessing(t interface {
	mock.TestingT
	Cleanup(func())
}) *Processing {
	mock := &Processing{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
